[pytest]
addopts = --slowmo 500 --html=report.html --self-contained-html
testpaths = tests
bdd_features_base_dir = features
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    login: Login scenarios
    user: User management scenarios
